[package]
name = "torii-poem"
version = "0.5.2"
edition.workspace = true
repository.workspace = true
license.workspace = true


[dependencies]
torii = { path = "../torii", version = "0.5.2", default-features = false }
torii-core = { path = "../torii-core", version = "0.5.1" }
poem = { version = "3.1", features = ["cookie"] }
tracing.workspace = true
